sudo: required

language: go

services:
  - docker

go:
- "1.10"
- "1.11.x"

env:
- MONGODB_VERSION=4.0
- MONGODB_VERSION=4.1

before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- sleep 5
- scripts/start-dev-stack.sh docker
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 8.14.0

script:
- cp example.muckity.yml muckity.yml
- go test -v ./...
- go run main.go
- npm install
- npm run test

cache:
  directories:
  - node_modules