version: '3.7'

services:

  mongo:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: muckity
      MONGO_INITDB_ROOT_PASSWORD: muckity
    volumes:
    - ./scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: muckity
      ME_CONFIG_MONGODB_ADMINPASSWORD: muckity

  muckity:
    build:
      context: .
      dockerfile: Dockerfile
    image: muckity:build
