version: '3.1'

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: muckity
      MONGO_INITDB_ROOT_USERNAME: muckity
      MONGO_INITDB_ROOT_PASSWORD: muckity
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    networks:
      default:
        aliases:
          - mongo
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: muckity
      ME_CONFIG_MONGODB_ADMINPASSWORD: muckity
    networks:
      default:
        aliases:
        - mongo-express
